#!/usr/bin/env python3
"""Extract the canonical catalogue array into one reusable data asset."""

from __future__ import annotations

import json
import re
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOGUE = ROOT / "products.html"
JSON_OUT = ROOT / "data" / "products.json"
JS_OUT = ROOT / "product-data.js"


def normalize(products: list[dict]) -> list[dict]:
    """Add the governed fields required by the export product data standard."""
    for product in products:
        specifications = {row[0]: row[1] for row in product.get("s", []) if isinstance(row, list) and len(row) == 2}
        product["identity"] = {
            "product_name": product.get("t"),
            "commercial_name": product.get("t"),
            "botanical_name": product.get("identity", {}).get("botanical_name"),
            "variety_or_grade": specifications.get("Variety") or specifications.get("Grade") or "Confirm in approved specification",
            "origin": specifications.get("Origin") or "India; producing region confirmed per contracted lot",
        }
        product["trade"] = {
            "hs_code": specifications.get("HS Code"),
            "moq": specifications.get("MOQ"),
            "container_20ft": product.get("l"),
            "container_40ft": "Confirmed for product, packing, route and legal weight limits",
            "packaging": product.get("p"),
            "private_label": "Available subject to product, artwork, material and order MOQ approval",
            "fob": "Request Current Price",
            "cif": "Available after destination, freight and insurance review",
            "port_of_loading": "Confirmed in the written quotation",
        }
        product["compliance"] = {
            "contract_basis": "Final specification, tolerance, test and document scope must be agreed in writing",
            "documents": ["Commercial Invoice", "Packing List", "Transport document", "Certificate of Origin when applicable"],
            "conditional_documents": ["Phytosanitary", "Fumigation", "COA", "Inspection report", "Health or destination-specific certificate"],
            "mrl_testing": "Confirmed by product, destination and contracted laboratory scope",
        }
    return products


def extract_array(text: str) -> str:
    marker = "const PRODUCT_DATA = ["
    start = text.index(marker) + len("const PRODUCT_DATA = ")
    depth = 0
    quote = None
    escaped = False
    for index in range(start, len(text)):
        char = text[index]
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            continue
        if char in {"'", '"', "`"}:
            quote = char
        elif char == "[":
            depth += 1
        elif char == "]":
            depth -= 1
            if depth == 0:
                return text[start:index + 1]
    raise ValueError("PRODUCT_DATA array is not balanced")


def main() -> int:
    text = CATALOGUE.read_text(encoding="utf-8")
    if "const PRODUCT_DATA = window.JFT_PRODUCT_DATA;" in text:
        data = json.loads(JSON_OUT.read_text(encoding="utf-8"))
    else:
        array = extract_array(text)
        program = "process.stdout.write(JSON.stringify(" + array + "))"
        with tempfile.NamedTemporaryFile("w", suffix=".js", encoding="utf-8", delete=False) as handle:
            handle.write(program)
            temporary_script = Path(handle.name)
        try:
            completed = subprocess.run(["node", str(temporary_script)], check=True, capture_output=True, text=True, encoding="utf-8")
        finally:
            temporary_script.unlink(missing_ok=True)
        data = json.loads(completed.stdout)
        JSON_OUT.parent.mkdir(exist_ok=True)
        pattern = re.compile(r"    const PRODUCT_DATA = \[.*?\n    \];", re.S)
        text, count = pattern.subn("    const PRODUCT_DATA = window.JFT_PRODUCT_DATA;", text, count=1)
        if count != 1:
            raise RuntimeError("Could not replace embedded PRODUCT_DATA")
        script_tag = '  <script src="product-data.js"></script>\n'
        anchor = "  <script>\n    const PRODUCT_DATA = window.JFT_PRODUCT_DATA;"
        text = text.replace(anchor, script_tag + anchor, 1)
        CATALOGUE.write_text(text, encoding="utf-8")

    data = normalize(data)
    JSON_OUT.parent.mkdir(exist_ok=True)
    JSON_OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    JS_OUT.write_text(
        "/* Generated by scripts/build_product_master.py; edit data/products.json through the governed product workflow. */\n"
        "window.JFT_PRODUCT_DATA = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"Canonical product master: {len(data)} records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
