#!/usr/bin/env python3
"""Build the client dictionary used by shared header/footer fragments."""

from __future__ import annotations

import json

from translate_fallback_pages import CACHE_PATH, LOCALES, ROOT, collect_strings, translate_values


def main() -> int:
    cache = json.loads(CACHE_PATH.read_text(encoding="utf-8")) if CACHE_PATH.exists() else {}
    values = collect_strings([ROOT / "header.html", ROOT / "footer.html"])
    dictionaries = {language: translate_values(language, values, cache) for language in LOCALES}
    CACHE_PATH.write_text(json.dumps(cache, ensure_ascii=False, indent=2), encoding="utf-8")
    payload = json.dumps(dictionaries, ensure_ascii=False, separators=(",", ":"))
    script = f'''/* Generated by scripts/build_locale_ui.py. */
(function () {{
  "use strict";
  const locale = location.pathname.split("/").filter(Boolean)[0];
  const dictionaries = {payload};
  const dictionary = dictionaries[locale];
  if (!dictionary) return;
  const skip = new Set(["SCRIPT", "STYLE", "NOSCRIPT", "CODE", "PRE", "SVG"]);
  function translateText(node) {{
    if (!node.parentElement || skip.has(node.parentElement.tagName)) return;
    const raw = node.nodeValue || "";
    const key = raw.replace(/\\s+/g, " ").trim();
    if (!dictionary[key]) return;
    node.nodeValue = raw.match(/^\\s*/)[0] + dictionary[key] + raw.match(/\\s*$/)[0];
  }}
  function translateElement(element) {{
    if (!(element instanceof Element) || skip.has(element.tagName)) return;
    for (const attribute of ["title", "placeholder", "aria-label"]) {{
      const value = element.getAttribute(attribute);
      const key = value && value.replace(/\\s+/g, " ").trim();
      if (key && dictionary[key]) element.setAttribute(attribute, dictionary[key]);
    }}
    for (const node of element.childNodes) {{
      if (node.nodeType === Node.TEXT_NODE) translateText(node);
      else if (node.nodeType === Node.ELEMENT_NODE) translateElement(node);
    }}
  }}
  function apply() {{
    for (const selector of ["#header-placeholder", "#footer-placeholder"]) {{
      const root = document.querySelector(selector);
      if (root) translateElement(root);
    }}
  }}
  apply();
  new MutationObserver(apply).observe(document.documentElement, {{ childList: true, subtree: true }});
  addEventListener("load", () => {{ apply(); setTimeout(apply, 250); }}, {{ once: true }});
}})();
'''
    (ROOT / "locale-ui.js").write_text(script, encoding="utf-8", newline="\n")
    print(f"Generated locale-ui.js with {len(values)} shared strings in {len(LOCALES)} languages.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
