#!/usr/bin/env python3
"""Build the client dictionary used by shared header/footer fragments.

Deterministic and network-free by construction: every translation must
already exist in data/localized-copy-cache.json. This script never imports
or calls anything that reaches translate.googleapis.com (or any other
network service) -- if a header/footer string is new or was never
translated, this script fails loudly (STEP 5/7 of the localization
determinism phase) instead of silently calling out to the network or
shipping stale/incomplete output.

To add a missing translation, use scripts/translate_fallback_pages.py's
network-capable authoring path (or add the entry to the cache directly),
then re-run this script.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from translate_fallback_pages import CACHE_PATH, LOCALES, ROOT, collect_strings, require_cached_translations, TranslationCoverageError

LOCALE_UI_PATH = ROOT / "locale-ui.js"


def compute_dictionaries(values: list[str], cache: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    """Pure function: source values + governed cache -> per-locale dictionaries.

    Shared by this script and scripts/audit_locale_ui.py so the "would this
    regenerate to something different" check never drifts from what actually
    ships. Raises TranslationCoverageError if any locale's cache coverage is
    incomplete for the given values -- never touches the network.
    """
    dictionaries: dict[str, dict[str, str]] = {}
    for language in LOCALES:
        translated = require_cached_translations(language, values, cache)
        dictionaries[language] = {
            source: translated[source] for source in values if translated[source] != source
        }
    return dictionaries


def render_script(values: list[str], dictionaries: dict[str, dict[str, str]]) -> str:
    """Pure function: dictionaries -> the exact locale-ui.js file contents."""
    payload = json.dumps(dictionaries, ensure_ascii=False, separators=(",", ":"))
    return f'''/* Generated by scripts/build_locale_ui.py. */
(function () {{
  "use strict";
  const locale = location.pathname.split("/").filter(Boolean)[0];
  const dictionaries = {payload};
  const dictionary = dictionaries[locale];
  if (!dictionary) return;
  const skip = new Set(["SCRIPT", "STYLE", "NOSCRIPT", "CODE", "PRE", "SVG"]);
  function translateText(node) {{
    if (!node.parentElement || skip.has(node.parentElement.tagName)) return;
    const raw = node.nodeValue || "";
    const key = raw.replace(/\\s+/g, " ").trim();
    if (!dictionary[key]) return;
    node.nodeValue = raw.match(/^\\s*/)[0] + dictionary[key] + raw.match(/\\s*$/)[0];
  }}
  function translateElement(element) {{
    if (!(element instanceof Element) || skip.has(element.tagName)) return;
    for (const attribute of ["title", "placeholder", "aria-label"]) {{
      const value = element.getAttribute(attribute);
      const key = value && value.replace(/\\s+/g, " ").trim();
      if (key && dictionary[key]) element.setAttribute(attribute, dictionary[key]);
    }}
    for (const node of element.childNodes) {{
      if (node.nodeType === Node.TEXT_NODE) translateText(node);
      else if (node.nodeType === Node.ELEMENT_NODE) translateElement(node);
    }}
  }}
  function apply() {{
    for (const selector of ["#header-placeholder", "#footer-placeholder"]) {{
      const root = document.querySelector(selector);
      if (root) translateElement(root);
    }}
  }}
  apply();
  new MutationObserver(apply).observe(document.documentElement, {{ childList: true, subtree: true }});
  addEventListener("load", () => {{ apply(); setTimeout(apply, 250); }}, {{ once: true }});
}})();
'''


def main() -> int:
    cache = json.loads(CACHE_PATH.read_text(encoding="utf-8")) if CACHE_PATH.exists() else {}
    values = collect_strings([ROOT / "header.html", ROOT / "footer.html"])

    try:
        dictionaries = compute_dictionaries(values, cache)
    except TranslationCoverageError as error:
        print(f"[FAIL] {error}", file=sys.stderr)
        print(
            "[FAIL] build_locale_ui.py cannot run to completion offline until the cache is complete. "
            "Add the missing translation(s) to data/localized-copy-cache.json (directly, or via "
            "scripts/translate_fallback_pages.py's network-capable authoring path) and re-run.",
            file=sys.stderr,
        )
        return 1

    script = render_script(values, dictionaries)
    LOCALE_UI_PATH.write_text(script, encoding="utf-8", newline="\n")
    print(f"Generated locale-ui.js with {len(values)} shared strings in {len(LOCALES)} languages.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
