# -*- coding: utf-8 -*-
"""Per-category bespoke content, grounded only in real data/products.json facts."""

CATEGORIES = {
    "rice": {
        "slug": "rice-exporter-india.html",
        "label": "Rice",
        "icon": "fa-seedling",
        "title": "Indian Rice Exporter | Basmati &amp; Non-Basmati | JFT Agro Overseas",
        "meta": "JFT Agro Overseas exports 20 Indian rice grades, including Basmati, IR-64 parboiled, Silky Sortex and Samba, with published specifications, HS codes and MOQ.",
        "h1": "Indian Rice <em>Exporter</em>",
        "hero_sub": "20 rice grades across Basmati and non-Basmati categories, each with a published reference specification, HS code, MOQ and packing option -- confirmed for the destination and contract before shipment.",
        "intro": "JFT Agro Overseas exports 20 distinct Indian rice grades spanning Basmati (1121, 1401, 1509 and 1718, in Golden Sella, Steam, Raw and White Sella forms), parboiled IR-64 in 5% and 10% broken grades, Silky Sortex white and short-grain rice in 5% and 25% broken grades, 100% broken rice, Samba rice and PR-11 rice. Each grade is a separate product page with its own specification table -- length, moisture, broken percentage, purity -- because buyers sourcing rice typically need one specific grade, not a general rice inquiry.",
        "selection": "Rice grades are distinguished primarily by variety (Basmati vs. non-Basmati), broken percentage, and processing (raw, steam, parboiled, or sella/golden sella). The correct grade depends on the buyer's destination market and intended use -- Basmati grades serve premium retail and foodservice markets, while IR-64 and broken-rice grades serve bulk food-security and processing markets. Every product page states the reference HS code, MOQ and packing options; the signed specification and an approved sample control the actual order.",
        "markets_note": "Rice from this catalogue currently ships to UAE, Kuwait, Saudi Arabia, Iraq, Iran and West African markets including Benin, among others -- see each product's own page for its specific documented markets.",
        "logistics": [("logistics/mundra-rice-exports/", "Mundra rice export route"), ("logistics/nhava-sheva-agro-exports/", "Nhava Sheva agro export route")],
    },
    "spices": {
        "slug": "spices-exporter-india.html",
        "label": "Spices",
        "icon": "fa-pepper-hot",
        "title": "Indian Spices Exporter | Turmeric, Chilli &amp; Cumin | JFT Agro",
        "meta": "JFT Agro Overseas exports 17 Indian spice products including turmeric, dry red chilli, cumin and coriander, each with a published specification and HS code.",
        "h1": "Indian Spices <em>Exporter</em>",
        "hero_sub": "17 spice products -- turmeric, chilli, cumin, coriander, pepper, cardamom and more -- each with its own HS code, specification and packing reference.",
        "intro": "JFT Agro Overseas exports 17 Indian spice products: turmeric finger and powder, dry ginger and powder, fennel, fenugreek, coriander seeds, cumin seeds, dry red chilli, tamarind, ajwain, bay leaf, whole nutmeg and powder, black pepper and powder, curry powder, celery seeds and powder, dill seeds and powder, mustard seeds and powder, and green cardamom. Spice buyers typically source by specific commodity and grade (e.g. a curcumin-content threshold for turmeric, or a Scoville/colour grade for chilli), which is why each spice is its own product page with its own specification.",
        "selection": "Spice specifications vary by product: turmeric is graded on curcumin content, chilli on heat (Scoville units) and colour (ASTA), and most spices carry moisture, purity, foreign-matter and admixture limits. HS codes differ by spice (17 distinct HS codes across this catalogue), which matters for customs classification and duty calculation at the destination.",
        "markets_note": "This spice catalogue's most frequently documented markets are the USA, UK, UAE, Europe, Japan and Saudi Arabia.",
        "logistics": [],
    },
    "herbs": {
        "slug": "herbs-seeds-exporter-india.html",
        "label": "Herbs &amp; Seeds",
        "icon": "fa-leaf",
        "title": "Indian Herbs &amp; Seeds Exporter | Senna, Psyllium Husk | JFT Agro",
        "meta": "JFT Agro Overseas exports 15 Indian herb and seed products including senna, psyllium husk, moringa and henna, each with a published specification and HS code.",
        "h1": "Indian Herbs &amp; Seeds <em>Exporter</em>",
        "hero_sub": "15 herb and functional-seed products -- senna, psyllium husk, moringa, henna and cassia tora among them -- for pharmaceutical, nutraceutical and industrial buyers.",
        "intro": "JFT Agro Overseas exports 15 herb and functional-seed products: senna leaves and pods, asaliya seeds, black himaj, basil seeds, cassia tora seeds and meal, galangal root, akarkara root, moringa leaves and powder, psyllium husk, henna leaves and powder, and wheat grass powder. These products serve pharmaceutical, nutraceutical, cosmetic and industrial buyers more often than food-retail buyers, which shapes the specification and documentation each one needs.",
        "selection": "Herb and functional-seed buyers typically specify active-content or purity thresholds relevant to their end use (for example, sennoside content for senna, or swelling factor for psyllium husk) rather than the culinary-grade metrics used for spices. Each product page states its own reference specification; 10 distinct HS codes apply across this group.",
        "markets_note": "This group's most frequently documented markets are the USA, Europe, the Middle East, China, Japan and Vietnam.",
        "logistics": [],
    },
    "oilseeds": {
        "slug": "oilseeds-exporter-india.html",
        "label": "Oilseeds",
        "icon": "fa-droplet",
        "title": "Indian Oilseeds Exporter | Sesame, Groundnut, Soya | JFT Agro",
        "meta": "JFT Agro Overseas exports 5 Indian oilseed products including sesame, groundnuts, soya bean and sunflower seeds, with published specifications and HS codes.",
        "h1": "Indian Oilseeds <em>Exporter</em>",
        "hero_sub": "5 oilseed products for crushing, food and confectionery use, each with its own specification and HS code.",
        "intro": "JFT Agro Overseas exports 5 Indian oilseed products: sesame seeds (natural and hulled), groundnuts (peanuts), soya bean, sunflower seeds (in shell) and black cumin seeds (nigella). Oilseed buyers generally split into two groups -- crushing/processing buyers focused on oil content and yield, and food/confectionery buyers focused on size grading, colour and cleanliness -- and the correct product page states which specification applies.",
        "selection": "Oil content, foreign-matter percentage, moisture and admixture are the primary specification fields for crushing buyers; size and colour grading matter more for food-use sesame and confectionery-grade groundnuts. 5 distinct HS codes apply across this group.",
        "markets_note": "This group's most frequently documented markets are the USA, Europe, Vietnam, the Middle East and China.",
        "logistics": [],
    },
    "feed": {
        "slug": "animal-feed-exporter-india.html",
        "label": "Animal Feed Inputs",
        "icon": "fa-cow",
        "title": "Indian Animal Feed Exporter | Maize, Millet, DORB | JFT Agro",
        "meta": "JFT Agro Overseas exports 15 Indian animal-feed inputs including yellow maize, sorghum, millets, oil cakes and DORB, each with a published specification and HS code.",
        "h1": "Indian Animal Feed Input <em>Exporter</em>",
        "hero_sub": "15 feed-grade grain, millet and oil-cake products for compound-feed manufacturers, each with a published specification and HS code.",
        "intro": "JFT Agro Overseas exports 15 animal-feed input products: yellow maize (corn), white sorghum (jowar), green millet (bajra), grey millet, red millet, safflower seeds, sunflower seeds, maize grits, soybean meal (DOC), deoiled rice bran (DORB), groundnut oil cake, barley seeds, corn gluten meal, cotton seed oil cake and buckwheat. Feed-input buyers specify by protein/oil/fibre content and admixture limits relevant to compound-feed formulation, which differs from the food-grade specifications used for the same grains sold for human consumption.",
        "selection": "Protein content (for meals and oil cakes), oil/fat content, fibre, moisture and admixture are the primary specification fields buyers request for feed-input use. 14 distinct HS codes apply across this group -- confirm the correct code for the intended feed-vs-food use before quoting.",
        "markets_note": "This group's most frequently documented markets are Vietnam, the Middle East, Africa, Europe, Bangladesh and China.",
        "logistics": [],
    },
    "flour": {
        "slug": "flour-exporter-india.html",
        "label": "Flour &amp; Milled Grains",
        "icon": "fa-bowl-food",
        "title": "Indian Flour Exporter | Chakki Atta, Maida, Semolina | JFT Agro",
        "meta": "JFT Agro Overseas exports 5 Indian milled-flour products including wheat flour, maida, semolina and corn flour, each with a published specification and HS code.",
        "h1": "Indian Flour &amp; Milled Grain <em>Exporter</em>",
        "hero_sub": "5 milled-flour products -- wheat flour, maida, semolina, corn flour and corn starch -- each with a published specification and HS code.",
        "intro": "JFT Agro Overseas exports 5 milled-flour products: wheat flour (chakki fresh atta), maida (refined wheat flour), semolina (sooji/rava), corn flour (maize flour) and corn starch. These are milled products with their own processing and packaging considerations -- ash content, gluten/starch content, granulation and moisture -- distinct from the raw-grain specifications used for wheat itself.",
        "selection": "Ash content, granulation/mesh size, gluten content (for wheat-based flours) and moisture are the primary specification fields. Retail-pack buyers and bulk-industrial buyers typically need different packaging references, both stated on each product page.",
        "markets_note": "This group's most frequently documented markets are UAE, Sri Lanka, Saudi Arabia, the USA, the UK and Somalia.",
        "logistics": [],
    },
    "wheat": {
        "slug": "wheat-exporter-india.html",
        "label": "Wheat",
        "icon": "fa-wheat-awn",
        "title": "Indian Milling Wheat Exporter | JFT Agro Overseas",
        "meta": "JFT Agro Overseas exports Indian milling wheat with a published specification, HS code and MOQ for bulk export to South Asian and Middle Eastern markets.",
        "h1": "Indian Milling Wheat <em>Exporter</em>",
        "hero_sub": "Milling wheat with a published specification, HS code and MOQ, documented for Bangladesh, Yemen, Nepal, UAE and Sri Lanka markets.",
        "intro": "JFT Agro Overseas exports Indian milling wheat as a single, focused product line rather than multiple grades -- this catalogue currently lists one milling wheat product with its own reference specification, HS code and MOQ.",
        "selection": "Milling wheat is specified on protein content, moisture, foreign matter, and falling number (a measure of sprout damage relevant to milling performance). The product page states the current reference specification; the signed specification and approved sample control the actual order.",
        "markets_note": "This product's documented markets are Bangladesh, Yemen, Nepal, UAE and Sri Lanka.",
        "logistics": [],
    },
    "sugar": {
        "slug": "sugar-exporter-india.html",
        "label": "Sugar",
        "icon": "fa-cubes",
        "title": "Indian Sugar S-30 Supplier | JFT Agro Overseas",
        "meta": "JFT Agro Overseas supplies Indian S-30 sugar subject to prevailing export policy, with current regulatory status published and verified on request.",
        "h1": "Indian Sugar <em>Supplier</em>",
        "hero_sub": "S-30 sugar supply, with current Indian export-policy status published and dated on the product page -- confirmed before quotation, not assumed.",
        "intro": "JFT Agro Overseas lists Indian S-30 sugar as a single, closely policy-governed product line. Indian sugar export is subject to government licensing and periodic restriction, so this product's own page carries dated, sourced regulatory information and an explicit statement that supply availability is confirmed before quotation rather than promised in advance.",
        "selection": "Sugar grade (S-30), polarization, colour/ICUMSA and moisture are the specification fields buyers request. Because export availability depends on current government policy, the product page itself -- not this category page -- is the authoritative source for today's regulatory status.",
        "markets_note": "This product's documented markets are Sudan, Somalia, Indonesia, Sri Lanka and Bangladesh.",
        "logistics": [],
    },
    "raisins": {
        "slug": "raisins-exporter-india.html",
        "label": "Raisins",
        "icon": "fa-apple-whole",
        "title": "Indian Raisins (Kishmish) Exporter | JFT Agro Overseas",
        "meta": "JFT Agro Overseas exports Indian raisins (kishmish) with a published specification, HS code and MOQ for bulk export to Europe, Russia and the Middle East.",
        "h1": "Indian Raisins <em>Exporter</em>",
        "hero_sub": "Indian raisins (kishmish) with a published specification, HS code and MOQ, documented for Europe, Russia, the Middle East and US markets.",
        "intro": "JFT Agro Overseas exports Indian raisins (kishmish) as a single, focused product line, with its own reference specification, HS code and MOQ.",
        "selection": "Raisins are specified on size grading, colour, moisture and foreign-matter content. The product page states the current reference specification; the signed specification and an approved sample control the actual order.",
        "markets_note": "This product's documented markets are Europe, Russia, the Middle East and the USA.",
        "logistics": [],
    },
    "pulses": {
        "slug": "pulses-exporter-india.html",
        "label": "Pulses",
        "icon": "fa-circle",
        "title": "Indian Pulses Exporter | Chickpeas, Mung, Toor Dal | JFT Agro",
        "meta": "JFT Agro Overseas exports 4 Indian pulse products -- yellow peas, chickpeas, green mung beans and toor dal -- each with a published specification and HS code.",
        "h1": "Indian Pulses <em>Exporter</em>",
        "hero_sub": "4 pulse products -- yellow peas, chickpeas, green mung beans and toor dal -- each with a published specification and HS code.",
        "intro": "JFT Agro Overseas exports 4 Indian pulse products: yellow peas (matar), chickpeas (kabuli), green mung beans and toor dal (split pigeon pea). Pulse buyers typically specify by count-per-100g or size grading, moisture, foreign matter, and split/whole form -- each product page states the applicable reference specification.",
        "selection": "Size/count grading, moisture, foreign-matter percentage and split-vs-whole form are the primary specification fields. 4 distinct HS codes apply across this group.",
        "markets_note": "This group's documented markets include Canada, Russia, Australia, Turkey, UAE, Saudi Arabia, Vietnam and China.",
        "logistics": [],
    },
}
